apiVersion: v1
kind: Pod
metadata:
  name: simple-app
spec:
  containers:
  - name: web
    image: "mattruyffelaert/simple-app:v2"
    ports:
    - containerPort: 8080
  - name: redis
    image: "redis:alpine"

