apiVersion: v1
kind: Pod
metadata:
  name: simple-app
spec:
  containers:
  - name: web
    image: docker.io/library/simple_python_app_web    
    ports:
    - containerPort: 8080
  #- name: redis
  #  image: "redis:alpine"
