on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
      
      - name: validate the chart can be built
        id: helm-check
        run: helm install sample-app simple-app/ --debug --dry-run
      
      - name: test if it works 
        if: contains(steps.helm-check.output, 'INSTALLATION FAILED') == false
        run: echo 'This is a valid push'
        
