on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      
      - name: validate the chart can be built
        id: helm-check
        run: helm install sample-app .
      
      - name: test if it works 
        if: contains(steps.helm-check.output, "Error: INSTALLATION FAILED") == false
        run: echo "This is a valid push"
        
